### ISSUE TITLE
Add navigation 

### ISSUE THREAD

**Issue by morelmiles** [CodeForUganda/service-charts-ug-#1]
Add a navigation bar with all the links to the resources that need  to be accessed.

**Comment by Harshith2255** [comment]
Hi
I would like to contribute to this

**Comment by morelmiles** [comment]
Hey, go right ahead.



---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by Harshith2255** [comment]
but i dont knoe javascript

**Comment by morelmiles** [comment]
What do you want to use? Because the code base is in Reactjs.

---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by Harshith2255** [comment]
I actually only know HTML and css.

**Comment by morelmiles** [comment]
Do you know bootstrap? Because that's what we intend to use for styling.
Normal CSS takes a lot of time


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by chhatrapalsinhzala007** [comment]
Hyy @morelmiles.

Can I also contribute to this ? 

I will use bootstrap to create navigation.

**Comment by morelmiles** [comment]
Yes, you can do that.
Do you know React?


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by chhatrapalsinhzala007** [comment]
Yes little bit.

Why ?

**Comment by morelmiles** [comment]
Because the code base is in Reactjs. I can guide you.


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by chhatrapalsinhzala007** [comment]
Okk.

Yes please it will be great if you guide me.
